/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP ProBook
 */
public class FrmMenu extends javax.swing.JFrame {

    HashTable theHash = new HashTable();
    DataArray theList = new DataArray();
    Heap theHeap = new Heap();
    LocalDateTime tanggal = LocalDateTime.now();
    int tanggal_now = tanggal.getDayOfMonth();
    Object bulan_now = tanggal.getMonth();
    int tahun_now = tanggal.getYear();
    String btnBlokRespond = "All";

    public FrmMenu() {
        initComponents();
        ContentPane.removeAll();
        ContentPane.repaint();
        ContentPane.revalidate();
        //tampilkan panel
        ContentPane.add(IntroPane);
        ContentPane.repaint();
        ContentPane.revalidate();
        jButton1.setBackground(new java.awt.Color(66, 72, 116));
        jButton2.setBackground(new java.awt.Color(66, 72, 116));
        jButton3.setBackground(new java.awt.Color(66, 72, 116));
        jLabel15.setVisible(true);
        rbA.setVisible(false);
        rbB.setVisible(false);
        rbC.setVisible(false);
        rbD.setVisible(false);
        btnEditConfirm.setVisible(false);
        btnEditCancel.setVisible(false);
        lblTanggal.setText(tanggal_now + " - " + bulan_now + " - " + tahun_now);
        cbPilihBulan.setSelectedItem(bulan_now.toString());
        load();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TitlePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        IntroPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ParkirPane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MasukPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNopolMasuk = new javax.swing.JTextField();
        cbJenisMasuk = new javax.swing.JComboBox();
        btnInsert = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        rbA = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        btnCheckBlok = new javax.swing.JButton();
        KeluarPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearchID = new javax.swing.JButton();
        btnSearchNOPOL = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblBiaya = new javax.swing.JLabel();
        txtNopolKeluar = new javax.swing.JTextField();
        txtJamEnterKeluar = new javax.swing.JTextField();
        txtJamExitKeluar = new javax.swing.JTextField();
        txtJenisKeluar = new javax.swing.JTextField();
        txtBlokKeluar = new javax.swing.JTextField();
        btnOut = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnEditCancel = new javax.swing.JButton();
        btnEditConfirm = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TampilPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTampil = new javax.swing.JTable();
        IncomePane = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnShowA = new javax.swing.JButton();
        btnShowB = new javax.swing.JButton();
        btnShowC = new javax.swing.JButton();
        btnShowD = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        IncomeHarianPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblIncomeHarian = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        lblPendapatanHarian = new javax.swing.JLabel();
        IncomeBulananPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIncomeBulanan = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        lblPendapatanBulanan = new javax.swing.JLabel();
        cbPilihBulan = new javax.swing.JComboBox();
        btnShowAll = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Background.setBackground(new java.awt.Color(66, 72, 116));

        Sidebar.setBackground(new java.awt.Color(66, 72, 116));
        Sidebar.setForeground(new java.awt.Color(66, 72, 116));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 72, 116));

        jButton3.setBackground(new java.awt.Color(66, 72, 116));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(166, 177, 225));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exit-16.png"))); // NOI18N
        jButton3.setText("KELUAR");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Sidebar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 353, 308, -1));

        jPanel4.setBackground(new java.awt.Color(66, 72, 116));

        jButton2.setBackground(new java.awt.Color(66, 72, 116));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(166, 177, 225));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-money-64.png"))); // NOI18N
        jButton2.setText("PENDAPATAN");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Sidebar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, 308, -1));

        jPanel5.setBackground(new java.awt.Color(66, 72, 116));

        jButton1.setBackground(new java.awt.Color(51, 51, 180));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(166, 177, 225));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-parking-64.png"))); // NOI18N
        jButton1.setText("MENU PARKIR");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Sidebar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        TitlePane.setBackground(new java.awt.Color(66, 72, 116));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(166, 177, 225));
        jLabel1.setText("DIGITAL PARKING");

        javax.swing.GroupLayout TitlePaneLayout = new javax.swing.GroupLayout(TitlePane);
        TitlePane.setLayout(TitlePaneLayout);
        TitlePaneLayout.setHorizontalGroup(
            TitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        TitlePaneLayout.setVerticalGroup(
            TitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        ContentPane.setLayout(new java.awt.CardLayout());

        IntroPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Car-Parking.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("TUGAS AKHIR MATA KULIAH STRUKTUR DATA");

        javax.swing.GroupLayout IntroPaneLayout = new javax.swing.GroupLayout(IntroPane);
        IntroPane.setLayout(IntroPaneLayout);
        IntroPaneLayout.setHorizontalGroup(
            IntroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(IntroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IntroPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        IntroPaneLayout.setVerticalGroup(
            IntroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        ContentPane.add(IntroPane, "card2");

        ParkirPane.setBackground(new java.awt.Color(66, 72, 116));
        ParkirPane.setPreferredSize(new java.awt.Dimension(625, 410));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        MasukPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("KENDARAAN MASUK");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("NOPOL");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("JENIS");

        txtNopolMasuk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNopolMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 72, 116), 3));
        txtNopolMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopolMasukActionPerformed(evt);
            }
        });
        txtNopolMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNopolMasukKeyTyped(evt);
            }
        });

        cbJenisMasuk.setBackground(new java.awt.Color(66, 72, 116));
        cbJenisMasuk.setForeground(new java.awt.Color(255, 255, 255));
        cbJenisMasuk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- PILIH JENIS KENDARAAN - ", "MOTOR", "MOBIL" }));
        cbJenisMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisMasukActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(66, 72, 116));
        btnInsert.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print-48.png"))); // NOI18N
        btnInsert.setText("CETAK TIKET");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("BLOK");

        buttonGroup1.add(rbA);
        rbA.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rbA.setText("A");

        buttonGroup1.add(rbB);
        rbB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rbB.setText("B");

        buttonGroup1.add(rbC);
        rbC.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rbC.setText("C");

        buttonGroup1.add(rbD);
        rbD.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rbD.setText("D");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("JUMLAH KENDARAAN :");

        lblJumlah.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblJumlah.setText("-");

        btnCheckBlok.setBackground(new java.awt.Color(66, 72, 116));
        btnCheckBlok.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        btnCheckBlok.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckBlok.setText("CEK BLOK KOSONG");
        btnCheckBlok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBlokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MasukPaneLayout = new javax.swing.GroupLayout(MasukPane);
        MasukPane.setLayout(MasukPaneLayout);
        MasukPaneLayout.setHorizontalGroup(
            MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasukPaneLayout.createSequentialGroup()
                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MasukPaneLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4))
                    .addGroup(MasukPaneLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MasukPaneLayout.createSequentialGroup()
                                .addComponent(rbC)
                                .addGap(18, 18, 18)
                                .addComponent(rbD))
                            .addGroup(MasukPaneLayout.createSequentialGroup()
                                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MasukPaneLayout.createSequentialGroup()
                                        .addComponent(rbA)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbB))
                                    .addGroup(MasukPaneLayout.createSequentialGroup()
                                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNopolMasuk)
                                            .addComponent(cbJenisMasuk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MasukPaneLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(MasukPaneLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnCheckBlok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(MasukPaneLayout.createSequentialGroup()
                                                        .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(1, 1, 1)))))))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        MasukPaneLayout.setVerticalGroup(
            MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MasukPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MasukPaneLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblJumlah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MasukPaneLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNopolMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJenisMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(34, 34, 34)
                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rbA)
                    .addComponent(rbB)
                    .addComponent(btnCheckBlok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(MasukPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbC)
                    .addComponent(rbD))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Masuk", MasukPane);

        KeluarPane.setBackground(new java.awt.Color(255, 255, 255));
        KeluarPane.setPreferredSize(new java.awt.Dimension(625, 410));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("ID TIKET/NOPOL");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("JENIS");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("JAM MASUK");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("JAM KELUAR");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("BIAYA");

        txtSearch.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        btnSearchID.setText("by ID");
        btnSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIDActionPerformed(evt);
            }
        });

        btnSearchNOPOL.setText("by NOPOL");
        btnSearchNOPOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNOPOLActionPerformed(evt);
            }
        });

        jLabel13.setText("SEARCH");

        jSeparator2.setBackground(new java.awt.Color(153, 51, 255));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("NOPOL");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("BLOK");

        jButton4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton4.setText("CHECK OUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblBiaya.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblBiaya.setText("-");

        txtNopolKeluar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtNopolKeluar.setEnabled(false);

        txtJamEnterKeluar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtJamEnterKeluar.setEnabled(false);

        txtJamExitKeluar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtJamExitKeluar.setEnabled(false);

        txtJenisKeluar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtJenisKeluar.setEnabled(false);

        txtBlokKeluar.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        txtBlokKeluar.setEnabled(false);

        btnOut.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnOut.setText("OUT");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnEditCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon-Small.png"))); // NOI18N
        btnEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCancelActionPerformed(evt);
            }
        });

        btnEditConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icon-OK.png"))); // NOI18N
        btnEditConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditConfirmActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KeluarPaneLayout = new javax.swing.GroupLayout(KeluarPane);
        KeluarPane.setLayout(KeluarPaneLayout);
        KeluarPaneLayout.setHorizontalGroup(
            KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeluarPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNopolKeluar)
                            .addComponent(txtJamEnterKeluar)
                            .addComponent(txtJamExitKeluar)
                            .addComponent(txtSearch))
                        .addGap(28, 28, 28)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(KeluarPaneLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtBlokKeluar))
                            .addComponent(jLabel13)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KeluarPaneLayout.createSequentialGroup()
                                .addComponent(btnSearchID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchNOPOL))
                            .addGroup(KeluarPaneLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(19, 19, 19)
                                .addComponent(txtJenisKeluar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KeluarPaneLayout.createSequentialGroup()
                                    .addComponent(btnEditConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1)
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(75, 75, 75)
                        .addComponent(lblBiaya)
                        .addGap(107, 107, 107)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(btnOut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        KeluarPaneLayout.setVerticalGroup(
            KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeluarPaneLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchID)
                            .addComponent(btnSearchNOPOL)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(txtNopolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJenisKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtJamEnterKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtJamExitKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBlokKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(KeluarPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20)
                .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(lblBiaya))
                    .addGroup(KeluarPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Keluar", KeluarPane);

        TampilPane.setBackground(new java.awt.Color(255, 255, 255));

        tbTampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbTampil);

        javax.swing.GroupLayout TampilPaneLayout = new javax.swing.GroupLayout(TampilPane);
        TampilPane.setLayout(TampilPaneLayout);
        TampilPaneLayout.setHorizontalGroup(
            TampilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TampilPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        TampilPaneLayout.setVerticalGroup(
            TampilPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TampilPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tampil", TampilPane);

        javax.swing.GroupLayout ParkirPaneLayout = new javax.swing.GroupLayout(ParkirPane);
        ParkirPane.setLayout(ParkirPaneLayout);
        ParkirPaneLayout.setHorizontalGroup(
            ParkirPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        ParkirPaneLayout.setVerticalGroup(
            ParkirPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        ContentPane.add(ParkirPane, "card2");

        IncomePane.setBackground(new java.awt.Color(255, 255, 255));
        IncomePane.setPreferredSize(new java.awt.Dimension(625, 410));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-money-bag-30.png"))); // NOI18N
        jLabel16.setText("TOTAL PENDAPATAN");

        btnShowA.setBackground(new java.awt.Color(66, 72, 116));
        btnShowA.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnShowA.setForeground(new java.awt.Color(255, 255, 255));
        btnShowA.setText("SHOW BLOK A");
        btnShowA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAActionPerformed(evt);
            }
        });

        btnShowB.setBackground(new java.awt.Color(66, 72, 116));
        btnShowB.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnShowB.setForeground(new java.awt.Color(255, 255, 255));
        btnShowB.setText("SHOW BLOK B");
        btnShowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBActionPerformed(evt);
            }
        });

        btnShowC.setBackground(new java.awt.Color(66, 72, 116));
        btnShowC.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnShowC.setForeground(new java.awt.Color(255, 255, 255));
        btnShowC.setText("SHOW BLOK C");
        btnShowC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCActionPerformed(evt);
            }
        });

        btnShowD.setBackground(new java.awt.Color(66, 72, 116));
        btnShowD.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnShowD.setForeground(new java.awt.Color(255, 255, 255));
        btnShowD.setText("SHOW BLOK D");
        btnShowD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDActionPerformed(evt);
            }
        });

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        IncomeHarianPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(66, 72, 116), null));

        tblIncomeHarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane3.setViewportView(tblIncomeHarian);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setText("TOTAL PENDAPATAN  :");

        lblPendapatanHarian.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPendapatanHarian.setText("-");

        javax.swing.GroupLayout IncomeHarianPaneLayout = new javax.swing.GroupLayout(IncomeHarianPane);
        IncomeHarianPane.setLayout(IncomeHarianPaneLayout);
        IncomeHarianPaneLayout.setHorizontalGroup(
            IncomeHarianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomeHarianPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IncomeHarianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IncomeHarianPaneLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPendapatanHarian)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        IncomeHarianPaneLayout.setVerticalGroup(
            IncomeHarianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomeHarianPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IncomeHarianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblPendapatanHarian))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Harian", IncomeHarianPane);

        IncomeBulananPane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(66, 72, 116), null));

        tblIncomeBulanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane4.setViewportView(tblIncomeBulanan);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("TOTAL PENDAPATAN  :");

        lblPendapatanBulanan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPendapatanBulanan.setText("-");

        cbPilihBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        cbPilihBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihBulanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IncomeBulananPaneLayout = new javax.swing.GroupLayout(IncomeBulananPane);
        IncomeBulananPane.setLayout(IncomeBulananPaneLayout);
        IncomeBulananPaneLayout.setHorizontalGroup(
            IncomeBulananPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomeBulananPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IncomeBulananPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IncomeBulananPaneLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPendapatanBulanan))
                    .addComponent(cbPilihBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        IncomeBulananPaneLayout.setVerticalGroup(
            IncomeBulananPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomeBulananPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbPilihBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IncomeBulananPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblPendapatanBulanan))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Bulanan", IncomeBulananPane);

        btnShowAll.setBackground(new java.awt.Color(66, 72, 116));
        btnShowAll.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnShowAll.setForeground(new java.awt.Color(255, 255, 255));
        btnShowAll.setText("SHOW ALL");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setText("TANGGAL HARI INI");

        lblTanggal.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTanggal.setText("01 - January - 2019");

        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IncomePaneLayout = new javax.swing.GroupLayout(IncomePane);
        IncomePane.setLayout(IncomePaneLayout);
        IncomePaneLayout.setHorizontalGroup(
            IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncomePaneLayout.createSequentialGroup()
                        .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(lblTanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IncomePaneLayout.createSequentialGroup()
                        .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane2)))
                .addContainerGap())
        );
        IncomePaneLayout.setVerticalGroup(
            IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePaneLayout.createSequentialGroup()
                .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncomePaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(btnShowAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTanggal)))
                    .addGroup(IncomePaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addGroup(IncomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncomePaneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnShowA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );

        ContentPane.add(IncomePane, "card2");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //hapus panel
        ContentPane.removeAll();
        ContentPane.repaint();
        ContentPane.revalidate();
        //tampilkan panel
        ContentPane.add(ParkirPane);
        ContentPane.repaint();
        ContentPane.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        tampil();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        masuk();
        tampil();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtNopolMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopolMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopolMasukActionPerformed

    private void txtNopolMasukKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNopolMasukKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtNopolMasukKeyTyped

    private void cbJenisMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisMasukActionPerformed
        buttonGroup1.clearSelection();
        if (cbJenisMasuk.getSelectedItem().equals("MOBIL")) {
            jLabel15.setVisible(true);
            rbA.setVisible(true);
            rbB.setVisible(true);
            rbC.setVisible(false);
            rbD.setVisible(false);
        } else if (cbJenisMasuk.getSelectedItem().equals("MOTOR")) {
            jLabel15.setVisible(true);
            rbA.setVisible(false);
            rbB.setVisible(false);
            rbC.setVisible(true);
            rbD.setVisible(true);
        }
    }//GEN-LAST:event_cbJenisMasukActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        this.btnBlokRespond = "All";
        tampilIncome();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String biayaText = String.valueOf(checkOut());
        lblBiaya.setText(biayaText);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIDActionPerformed
        SearchID();
    }//GEN-LAST:event_btnSearchIDActionPerformed

    private void btnCheckBlokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBlokActionPerformed
        Object sizeBlok = "A = " + theList.getBlokASize() + " / " + theList.getLBlok()
                + "\nB = " + theList.getBlokBSize() + " / " + theList.getLBlok()
                + "\nC = " + theList.getBlokCSize() + " / " + theList.getLBlok()
                + "\nD = " + theList.getBlokDSize() + " / " + theList.getLBlok();
        JOptionPane.showMessageDialog(null, sizeBlok);
    }//GEN-LAST:event_btnCheckBlokActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        tampilIncome();
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        int id = Integer.parseInt(txtSearch.getText());
        Data temp = theHash.find(id).getData();
        moveToHeap(temp);
        keluar();
        tampil();
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (txtSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang akan di Edit");
        } else {
            btnEdit.setEnabled(false);
            btnEditConfirm.setVisible(true);
            btnEditCancel.setVisible(true);
            txtNopolKeluar.setEnabled(true);
            txtJenisKeluar.setEnabled(true);
            txtBlokKeluar.setEnabled(true);
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCancelActionPerformed
        resetKeluar();
    }//GEN-LAST:event_btnEditCancelActionPerformed

    private void btnEditConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditConfirmActionPerformed
        update();
        resetKeluar();
        tampil();
    }//GEN-LAST:event_btnEditConfirmActionPerformed

    private void btnSearchNOPOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNOPOLActionPerformed
        SearchNopol();
    }//GEN-LAST:event_btnSearchNOPOLActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //hapus panel
        ContentPane.removeAll();
        ContentPane.repaint();
        ContentPane.revalidate();
        //tampilkan panel
        ContentPane.add(IncomePane);
        ContentPane.repaint();
        ContentPane.revalidate();
        tampilIncome();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnShowAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAActionPerformed
        this.btnBlokRespond = "A";
        tampilIncome();
    }//GEN-LAST:event_btnShowAActionPerformed

    private void btnShowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBActionPerformed
        this.btnBlokRespond = "B";
        tampilIncome();
    }//GEN-LAST:event_btnShowBActionPerformed

    private void btnShowCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCActionPerformed
        this.btnBlokRespond = "C";
        tampilIncome();
    }//GEN-LAST:event_btnShowCActionPerformed

    private void btnShowDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDActionPerformed
        this.btnBlokRespond = "D";
        tampilIncome();
    }//GEN-LAST:event_btnShowDActionPerformed

    private void cbPilihBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihBulanActionPerformed
        tampilIncome();
    }//GEN-LAST:event_cbPilihBulanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Data[] all = theHeap.getAllData();
        try {
            ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("data.bin"));
            os.writeObject(all);
            os.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Write AutoSaved....");
    }//GEN-LAST:event_formWindowClosing

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Serius mau hapus data?");
        if (input == 0) {
            try {
                theHeap.clear();
                JOptionPane.showMessageDialog(null, "Data terhapus");
                for (int i = 0; i < theHeap.getMaxSize(); i++) {
                    System.out.println(theHeap.getData(i));
                }
                System.out.println("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data tidak terhapus");
            }
        }
        String col[] = {"NOPOL", "JENIS", "BLOK", "WAKTU_MASUK", "WAKTU_KELUAR", "BIAYA"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblIncomeBulanan.setModel(tableModel);
        tblIncomeHarian.setModel(tableModel);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JPanel IncomeBulananPane;
    private javax.swing.JPanel IncomeHarianPane;
    private javax.swing.JPanel IncomePane;
    private javax.swing.JPanel IntroPane;
    private javax.swing.JPanel KeluarPane;
    private javax.swing.JPanel MasukPane;
    private javax.swing.JPanel ParkirPane;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel TampilPane;
    private javax.swing.JPanel TitlePane;
    private javax.swing.JButton btnCheckBlok;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditCancel;
    private javax.swing.JButton btnEditConfirm;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchNOPOL;
    private javax.swing.JButton btnShowA;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnShowB;
    private javax.swing.JButton btnShowC;
    private javax.swing.JButton btnShowD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbJenisMasuk;
    private javax.swing.JComboBox cbPilihBulan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblPendapatanBulanan;
    private javax.swing.JLabel lblPendapatanHarian;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JTable tbTampil;
    private javax.swing.JTable tblIncomeBulanan;
    private javax.swing.JTable tblIncomeHarian;
    private javax.swing.JTextField txtBlokKeluar;
    private javax.swing.JTextField txtJamEnterKeluar;
    private javax.swing.JTextField txtJamExitKeluar;
    private javax.swing.JTextField txtJenisKeluar;
    private javax.swing.JTextField txtNopolKeluar;
    private javax.swing.JTextField txtNopolMasuk;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        lblJumlah.setText(theList.getSizelbl());
        try {
            String col[] = {"ID", "NOPOL", "JENIS", "BLOK", "WAKTU_MASUK"};
            DefaultTableModel tableModel = new DefaultTableModel(col, 0);
            for (int i = 0; i < theList.getSize(); i++) {
                Object[] rowData = theList.getData(i);
                tableModel.addRow(rowData);
            }
            jTable1.setModel(tableModel);
            tbTampil.setModel(tableModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void tampilIncome() {
        tblIncomeBulanan.removeAll();
        tblIncomeHarian.removeAll();
        String col[] = {"NOPOL", "JENIS", "BLOK", "WAKTU_MASUK", "WAKTU_KELUAR", "BIAYA"};
        try {
            if (btnBlokRespond == "All") {
                DefaultTableModel tableModel = new DefaultTableModel(col, 0);
                for (int i = 0; i < theHeap.getSize(); i++) {
                    if (theHeap.getData(i).timeKeluar().getDayOfMonth() == tanggal_now && theHeap.getData(i).timeKeluar().getMonth().equals(bulan_now)) {
                        Object[] rowData = theHeap.getList(i);
                        tableModel.addRow(rowData);
                    }
                }
                tblIncomeHarian.setModel(tableModel);
                getTotalIncome();
            } else {
                DefaultTableModel tableModel = new DefaultTableModel(col, 0);
                for (int i = 0; i < theHeap.getSize(); i++) {
                    if (theHeap.getData(i).getBlok().equals(btnBlokRespond)) {
                        if (theHeap.getData(i).timeKeluar().getDayOfMonth() == tanggal_now && theHeap.getData(i).timeKeluar().getMonth().equals(bulan_now)) {
                            Object[] rowData = theHeap.getList(i);
                            tableModel.addRow(rowData);
                        }
                    }
                }
                tblIncomeHarian.setModel(tableModel);
                getTotalIncome();
            }

        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
        }
        try {
            if (btnBlokRespond == "All") {
                DefaultTableModel tableModel = new DefaultTableModel(col, 0);
                for (int i = 0; i < theHeap.getSize(); i++) {
                    if (theHeap.getData(i).getBulankeluar() == cbPilihBulan.getSelectedItem()) {
                        Object[] rowData = theHeap.getList(i);
                        tableModel.addRow(rowData);
                    }
                }
                tblIncomeBulanan.setModel(tableModel);
                getTotalIncome();
            } else {
                DefaultTableModel tableModel = new DefaultTableModel(col, 0);
                for (int i = 0; i < theHeap.getSize(); i++) {
                    if (theHeap.getData(i).getBulankeluar() == cbPilihBulan.getSelectedItem()) {
                        if (theHeap.getData(i).getBlok().equals(btnBlokRespond)) {
                            Object[] rowData = theHeap.getList(i);
                            tableModel.addRow(rowData);
                        }
                    }
                }
                tblIncomeBulanan.setModel(tableModel);
                getTotalIncome();
            }
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void getTotalIncome() {
        int totalBulanan = 0;
        for (int i = 0; i < tblIncomeBulanan.getRowCount(); i++) {
            String biaya = tblIncomeBulanan.getValueAt(i, 5).toString();
            int biaya1 = Integer.parseInt(biaya);
            totalBulanan += biaya1;
        }
        lblPendapatanBulanan.setText(String.valueOf(totalBulanan));
        int totalHarian = 0;
        for (int i = 0; i < tblIncomeHarian.getRowCount(); i++) {
            String biaya = tblIncomeHarian.getValueAt(i, 5).toString();
            int biaya1 = Integer.parseInt(biaya);
            totalHarian += biaya1;
        }
        lblPendapatanHarian.setText(String.valueOf(totalHarian));
    }

    private void masuk() {
        String nopol = txtNopolMasuk.getText();
        String jenis = cbJenisMasuk.getSelectedItem().toString();
        String blok = getSelectedBlok();
        Data curData;
        try {
            if (!theList.isEmpty(blok)) {
                JOptionPane.showMessageDialog(null, "Blok penuh");
            } else {
                if (nopol.equals("")) {
                    JOptionPane.showMessageDialog(null, "Masukkan no plat");
                } else if (cbJenisMasuk.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Pilih jenis kendaraan terlebih dahulu");
                } else {
                    try {
                        curData = theHash.insert(nopol, jenis, blok);
                        theList.insert(nopol, jenis, blok);
                        JOptionPane.showMessageDialog(null, "Data Masuk");
//                        cetak(curData);
                        reset();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Data Tidak Masuk");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Blok Kosong");
        }

    }

    private String getSelectedBlok() {
        String blok = null;
        if (rbA.isSelected()) {
            blok = "A";
        } else if (rbB.isSelected()) {
            blok = "B";
        } else if (rbC.isSelected()) {
            blok = "C";
        } else if (rbD.isSelected()) {
            blok = "D";
        }
        return blok;
    }

    private void keluar() {
        int id = Integer.parseInt(txtSearch.getText());
        if (txtJamExitKeluar.getText().equals("0.0")) {
            JOptionPane.showMessageDialog(null, "Tekan Checkout untuk menambahkan jam keluar !!");
        } else {
            try {
                theHash.delete(id);
                theList.delete(id);
                JOptionPane.showMessageDialog(null, "Data Keluar");
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private Data SearchID() {
        int id = Integer.parseInt(txtSearch.getText());
        Data currentSearch = theHash.find(id);
        try {
            String nopol = null, jenis = null, jamMasuk = null, jamKeluar = null, blok = null;
            if (theHash.find(id) != null) {
                nopol = currentSearch.getNopol();
                jenis = currentSearch.getJenis();
                jamMasuk = currentSearch.getJamMasuk();
                jamKeluar = currentSearch.getJamKeluar();
                blok = currentSearch.getBlok();
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ada");
            }
            txtNopolKeluar.setText(nopol);
            txtJenisKeluar.setText(jenis);
            txtJamEnterKeluar.setText(jamMasuk);
            txtJamExitKeluar.setText(jamKeluar);
            txtBlokKeluar.setText(blok);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak ada ID yang dicari");
        }
        return currentSearch;
    }

    private void SearchNopol() {
        try {
            String search = txtSearch.getText();
            Data currentSearch = theList.find(search);
            int id = 0;
            String nopol = null, jenis = null, jamMasuk = null, jamKeluar = null, blok = null;
            if (theList.find(search) != null) {
                id = currentSearch.getID();
                nopol = currentSearch.getNopol();
                jenis = currentSearch.getJenis();
                jamMasuk = currentSearch.getJamMasuk();
                jamKeluar = currentSearch.getJamKeluar();
                blok = currentSearch.getBlok();
            } else {
                JOptionPane.showMessageDialog(null, "Data Tidak ada");
            }
            txtSearch.setText(String.valueOf(id));
            txtNopolKeluar.setText(nopol);
            txtJenisKeluar.setText(jenis);
            txtJamEnterKeluar.setText(jamMasuk);
            txtJamExitKeluar.setText(jamKeluar);
            txtBlokKeluar.setText(blok);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak ada NOPOL yang dicari");
        }
    }

    private void updateJamKeluar() {
        int id = Integer.parseInt(txtSearch.getText());
        theHash.find(id).updateJamKeluar();
        SearchID();
    }

    private int checkOut() {
        updateJamKeluar();
        int id = Integer.parseInt(txtSearch.getText());
        Data dataOut = theHash.find(id);
        int biaya = 0, start = 0, selisih;
        LocalDateTime enter, exit;
        int enterJam, enterMenit, exitJam, exitMenit;
        String blok = dataOut.getBlok();
        switch (blok) {
            case "A":
                start = 5000;
                break;
            case "B":
                start = 4000;
                break;
            case "C":
                start = 3000;
                break;
            case "D":
                start = 3000;
                break;
        }
        enter = dataOut.timeMasuk();
        exit = dataOut.timeKeluar();
        enterJam = enter.getHour();
        enterMenit = enter.getMinute();
        exitJam = exit.getHour();
        exitMenit = exit.getMinute();
        if (enterMenit > 45 && enterMenit <= 59) {
            enterJam++;
        }
        if (exitMenit > 45 && exitMenit <= 59) {
            exitJam++;
        }

        selisih = exitJam - enterJam;
        if (selisih < 2) {
            return start;
        }
        switch (blok) {
            case "A":
                biaya = start + (selisih * 4000);
                break;
            case "B":
                biaya = start + (selisih * 3000);
                break;
            case "C":
                biaya = start + (selisih * 2000);
                break;
            case "D":
                biaya = start + (selisih * 2000);
                break;
        }
        return biaya;
    }

    private void update() {
        int id = Integer.parseInt(txtSearch.getText());
        String newNopol = txtNopolKeluar.getText();
        String newJenis = txtJenisKeluar.getText();
        String newBlok = txtBlokKeluar.getText();
        theHash.find(id).update(newNopol, newJenis, newBlok);
        theList.update(id).update(newNopol, newJenis, newBlok);
    }

    private void resetKeluar() {
        SearchID();
        btnEdit.setEnabled(true);
        btnEditConfirm.setVisible(false);
        btnEditCancel.setVisible(false);
        txtNopolKeluar.setEnabled(false);
        txtJenisKeluar.setEnabled(false);
        txtBlokKeluar.setEnabled(false);
    }

    private void reset() {
        txtNopolMasuk.setText("");
        txtSearch.setText("");
        txtNopolKeluar.setText("");
        txtJenisKeluar.setText("");
        txtBlokKeluar.setText("");
        txtJamEnterKeluar.setText("");
        txtJamExitKeluar.setText("");
        lblBiaya.setText("");
        cbJenisMasuk.setSelectedIndex(0);
    }

    public void moveToHeap(Data temp) {
        int biaya = Integer.parseInt(lblBiaya.getText());
        theHeap.insert(temp, biaya);
    }

    public void cetak(Data curData) {
        String tanggal = String.valueOf(curData.timeMasuk().getDayOfMonth());
        String bulan = String.valueOf(curData.timeMasuk().getMonth());
        String tahun = String.valueOf(curData.timeMasuk().getYear());

        PrintJob p = getToolkit().getPrintJob(this, "Cetak Tiket", null);

        Graphics g = p.getGraphics();
        g.setFont(new Font("Serif", Font.BOLD, 20));
        g.drawString("TIKET NO: " + curData.getID(), 200, 18);
        g.drawLine(10, 30, 600, 30);
        g.setFont(new Font("Serif", Font.BOLD, 60));
        g.drawString("ID : " + curData.getID(), 400, 100);
        g.setFont(new Font("Courier New", Font.PLAIN, 12));
        g.drawString("No. Pol", 10, 50);
        g.drawString(" : ", 100, 50);
        g.drawString(curData.getNopol(), 160, 50);

        g.drawString("Jenis", 10, 60);
        g.drawString(" : ", 100, 60);
        g.drawString(curData.getJenis(), 160, 60);

        g.drawString("Tanggal Masuk", 10, 70);
        g.drawString(" : ", 100, 70);
        g.drawString(tanggal + " - " + bulan + " - " + tahun, 160, 70);

        g.drawString("Jam Masuk", 10, 80);
        g.drawString(" : ", 100, 80);
        g.drawString(String.valueOf(curData.getJamMasuk()), 160, 80);

        g.drawString("Blok", 10, 90);
        g.drawString(" : ", 100, 90);
        g.drawString(String.valueOf(curData.getBlok()), 160, 90);

        g.setFont(new Font("Courier New", Font.PLAIN, 8));
        g.drawString("*Biaya parkir tergantung jenis kendaraan dan durasi parkir", 10, 150);

        p.end();
    }

    private void load() {
        try {
            ObjectInputStream is = new ObjectInputStream(new FileInputStream("data.bin"));
            Data[] inData = (Data[]) is.readObject();
//            JOptionPane.showMessageDialog(null, inData);
            for (Data inData1 : inData) {
//                System.out.println(inData1);
                if (inData1 != null) {
                    theHeap.insert(inData1, inData1.getBiaya());
                }
            }
            JOptionPane.showMessageDialog(null, "Read Successfully");
            is.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}
